version: '3.7'

services:
  db:
    image: postgres:13
    ports:
      - '5432:${DATABASE_PORT:-5432}'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=localhost
